### ISSUE TITLE
блок

### ISSUE THREAD

**Issue by Corn3333** [Crose212/claim_arbitrum#2]
https://github.com/Crose212/claim_arbitrum/blob/0f7355b26de155de5ab4657d155469754d826bb7/src/optional.rs#L15

Суть в том, что скрипт сработает если нужный блок будет равен текущему. Т.е. если мы захотим вывести после этого блока, мы не сможет. Надо ставить >= или <=, не вникал в код

**Comment by Crose212** [comment]
Код выходит из лупа и функция заканчивает работать когда блок станет нужным, больше не будет проверок на номер блока после этого

**Comment by Crose212** [comment]
Поменял на if needed_block < curr_block {
